env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

task:
  name: Build
  timeout_in: 2h
  container:
    image: xack21:latest
    cpu: 16
    memory: 64G
  chmod_script:
    - sudo chmod +x *
  # telegram_script:
    # - ./telegram
  download_script:
    - ./download_ccache
  sync_script:
    - ./sync
  monitor_background_script:
    - ./monitor
  build_script:
    - ./build
  upload_ccache_script:
    - ./upload
